# Generated by Django 3.0.4 on 2020-03-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_field',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
