# Generated by Django 3.0.4 on 2020-03-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_field',
            field=models.ImageField(default=0, upload_to='static/images'),
        ),
    ]
