# Generated by Django 3.0.4 on 2020-03-10 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
